<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLySanPham" Class="QuanLySanPHamDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Catalog" Member="Catalogs">
    <Type Name="Catalog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CatalogCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CatalogName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Catalog_Product" Member="Products" ThisKey="Id" OtherKey="CatalogId" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CatalogId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Catalog_Product" Member="Catalog" ThisKey="CatalogId" OtherKey="Id" Type="Catalog" IsForeignKey="true" />
    </Type>
  </Table>
</Database>